name: Daily Post

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: bot/requirements.txt

      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MAX_DAILY: "3"
          MAX_AGE_DAYS: "45"
        run: |
          chmod +x ./.github/scripts/start.sh
          ./.github/scripts/start.sh

      - name: Commit history
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily drop"
          file_pattern: bot/sent_urls.txt
          commit_user_name: G3kSec [GitHub Actions]
          commit_author: G3kSec <g3ksec@users.noreply.github.com>
