name: Daily Post
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    env:
      telegram: ${{secrets.TELEGRAM_TOKEN}}
      chat: ${{secrets.CHAT_ID}}
      discord: ${{secrets.DISCORD_WEBHOOK}}

    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Run script
        run: 
          chmod +x ./.github/scripts/start.sh && /usr/bin/bash ./.github/scripts/start.sh ${{env.telegram}} ${{env.chat}} ${{env.discord}}

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 💣 Automated Daily Post 🔥
          commit_user_name: Luciano Griffa [GitHub Actions]
          commit_user_email: lucianogriffa@protonmail.com
          commit_author: lucianogriffa
